#!/bin/bash

NAME="Wes van der Vleuten"
EMAIL="me@wes.cloud"


echo "osconfig by WesVleuten";
echo "Starting now...";
echo "----";

echo "Updating apt repositories";
sudo apt-get update -qq > /dev/null;

echo "Upgrading out of date packages";
sudo apt-get upgrade -qq > /dev/null;

echo "Installing i3";
sudo apt-get install i3 -qq > /dev/null;

echo "Installing git";
sudo apt-get install git -qq > /dev/null;
git config --global user.email "$EMAIL"
git config --global user.name "$NAME"

echo "Installing vim";
sudo apt-get install vim -qq > /dev/null;

echo "Installing xclip";
sudo apt-get install xclip -qq > /dev/null;

echo "Installing terminal profile";
dconf load /org/gnome/terminal/legacy/profiles:/ < gnome-terminal-profiles.dconf;

echo "Installing zsh";
sudo apt-get install zsh -qq > /dev/null;

if [ ! -d ~/.oh-my-zsh ]; then
	echo "Installing oh-my-zsh";

	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
	chsh -s $(which zsh);

	echo "[NOTICE] Please exit your terminal after installation";

else
	echo "Skipping oh-my-zsh";
fi

if [ ! -f ~/.vim/bundle/Vundle.vim/README.md ]; then
	echo "Installing Vundle";
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;
else
	echo "Skipping installing Vundle";
fi

if [ ! -f ~/.ssh/id_rsa ]; then
	echo "Generating id_rsa";
	ssh-keygen -t rsa -b 4096 -C "workstation" -f ~/.ssh/id_rsa;

	# make sure ssh-agent is running, then add id_rsa to the agent
	eval "$(ssh-agent -s)" > /dev/null;
	ssh-add ~/.ssh/id_rsa;

	# copy public key to clipboard
	echo "Copied public key to clipboard";
	xclip -sel clip < ~/.ssh/id_rsa.pub;
else
	echo "Skipping id_rsa";
fi

echo "Creating link for i3 config";
ln -f ./i3config ~/.config/i3/config;

echo "Creating link for i3status config";
ln -f ./i3status.conf ~/.config/i3/status.conf

echo "Creating link for .vimrc config";
ln -f ./vimrc ~/.vimrc;

echo "Adding vim header";
mkdir -p ~/.vim/after/plugin
ln -f ./wheader.vim ~/.vim/after/plugin

echo "Installing vim plugins";
vim +PluginInstall +qall;

echo "Setting timezone";
sudo timedatectl set-timezone 'Europe/Amsterdam';
echo "Please check if the date is set correctly!";
date;

